// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	demo1 "github.com/SYuan03/Day3/HertzServer/biz/router/demo1"
	demo2 "github.com/SYuan03/Day3/HertzServer/biz/router/demo2"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	demo2.Register(r)

	demo1.Register(r)

}
