// Code generated by Kitex v0.6.1. DO NOT EDIT.

package studentservice

import (
	server "github.com/cloudwego/kitex/server"
	demo2 "nju/apigw/kitex_gen/demo2"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler demo2.StudentService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
