// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"nju/apigw/clientprovider"
	"time"
)

func main() {
	clientprovider.IdlVersion["studentserviceA"] = "1"
	clientprovider.IdlVersion["studentserviceB"] = "1"
	go func() {
		for {
			clientprovider.UpdateCli("studentserviceA")
			clientprovider.UpdateCli("studentserviceB")
			time.Sleep(time.Second * 15)
		}
	}()
	h := server.Default()

	register(h)
	h.Spin()
}
