// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	//go func() {
	//	for {
	//		//clientprovider.UpdateCli("studentservice")
	//		//clientprovider.UpdateCli("studentservice2")
	//		time.Sleep(time.Second * 10)
	//	}
	//}()
	h := server.Default()

	register(h)
	h.Spin()
}
