// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"nju/apigw/clientprovider"
	"time"
)

func main() {
	go func() {
		for {
			clientprovider.UpdateCli("studentservice")
			clientprovider.UpdateCli("studentservice2")
			time.Sleep(time.Second * 10)
		}
	}()
	h := server.Default()

	register(h)
	h.Spin()
}
