// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"fmt"
)

// Apigw .
func Apigw(ctx context.Context, c *app.RequestContext) {
	// 获取整个请求的url
	header := c.Request.Header
	body := c.Request.Body

	fmt.Println(header)
	fmt.Println(body)

	c.JSON(consts.StatusOK, utils.H{
		"message": "Apigw",
	})
}
